### ISSUE TITLE
Login object accepts `authenticationToken` - This property of `Login` is deprecated and has been removed

### ISSUE THREAD

**Issue by paulw11** [kisi-inc/kisi-android-st2u-sdk-public#3]
The `Login` object requires the `secret` property from the JSON login, as `authentication_token` has been removed.

**Comment by ce07c3** [comment]
@agap please have a look - perhaps we need to adjust the same for iOS.

**Comment by agap** [comment]
@paulw11 thanks, great catch! I added this to version 0.7 and updated our README accordingly.

Thanks again!
