### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by chirag-vaghasiya** [kisi-inc/kisi-android-st2u-sdk-public#5]
The readme instruction and t2asample project no longer work with release 0.8 and need to be reviewed and updated. 

For example, references to Scram3 should be replaced with SecureUnlock. Also it seems a new parameter startWithProtocolVersion is introduced but nothing in the readme explains what it does and what value the caller should pass.

**Comment by agap** [comment]
Hello, Chirag!

Thanks for the ticket, I will update the readme and sample project.

Regarding `startWithProtocolVersion` - please pass `true` as a value. This is an internal thing that we're testing ourselves now, and passing `false` won't lead to any improvements in your side (on the contrary, it will only lead to failed unlocks).

**Comment by agap** [comment]
@chirag-vaghasiya I've just updated both the SDK documentation and the sample app that we have; thank you again for pointing that out!

**Comment by chirag-vaghasiya** [comment]
Thanks Artem
